#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/CMC_Gpo/DSCResources/CMC_Gpo/CMC_Gpo.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/CMC_Gpo/DSCResources/CMC_GpoExtendedRight/CMC_GpoExtendedRight.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/CMC_Gpo/DSCResources/CMC_GpoExtendedRight2/CMC_GpoExtendedRight2.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/CMC_Gpo/DSCResources/CMC_GpoExtendedRight3/CMC_GpoExtendedRight3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/CMC_Gpo/DSCResources/CMC_GpoInheritance/CMC_GpoInheritance.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/CMC_Gpo/DSCResources/CMC_GpoLink/CMC_GpoLink.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cBAM/DSCResources/cBAM_BatchFile/cBAM_BatchFile.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cBAM/DSCResources/cBAM_BatchFile2/cBAM_BatchFile2.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cBAM/DSCResources/cBAM_BatchFile3/cBAM_BatchFile3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cBAM/DSCResources/cBAM_DonnaBatchFile/cBAM_DonnaBatchFile.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cChoco/DSCResources/cChocoInstaller/cChocoInstaller.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cChoco/DSCResources/cChocoPackageInstall/cChocoPackageInstall.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cChoco/DSCResources/cChocoSource/cChocoSource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cComputer/DSCResources/cComputer/cComputer.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_Authorize/cDHCP_Authorize.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_Failover/cDHCP_Failover.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_Options/cDHCP_Options.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_Options2/cDHCP_Options2.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_Reservation/cDHCP_Reservation.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_Scope/cDHCP_Scope.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDHCP/DSCResources/cDHCP_SecurityGroup/cDHCP_SecurityGroup.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDns/DSCResources/cDns_ConditionalForwarder/cDns_ConditionalForwarder.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cDns/DSCResources/cDns_ConditionalForwarder2/cDns_ConditionalForwarder2.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_ActivateWindows/cMisc_ActivateWindows.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_ClusterResourceDependency/cMisc_ClusterResourceDependency.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_ClusterSubnetDelay/cMisc_ClusterSubnetDelay.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_ConfigureIPv4/cMisc_ConfigureIPv4.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_ConfigureORA/cMisc_ConfigureORA.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_CrewsAdaptor/cMisc_CrewsAdaptor.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_Disk/cMisc_Disk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_Disk_Set8dot3/cMisc_Disk_Set8dot3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_DispatcherService/cMisc_DispatcherService.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_DomainAdmins/cMisc_DomainAdmins.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_EnvVar/cMisc_EnvVar.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_FailoverClusterDisk/cMisc_FailoverClusterDisk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_FailoverFileServer/cMisc_FailoverFileServer.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_FailoverFileServer2/cMisc_FailoverFileServer2.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_InstallUnivocalPathServer/cMisc_InstallUnivocalPathServer.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_LocalGroup/cMisc_LocalGroup.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_MoveDisksToOwner/cMisc_MoveDisksToOwner.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_Passwordreq/cMisc_Passwordreq.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_Rename_Interface/cMisc_Rename_Interface.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_SetIPv6/cMisc_SetIPv6.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_SetWSUS/cMisc_SetWSUS.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_SuspendNode/cMisc_SuspendNode.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cMisc/DSCResources/cMisc_TimeSource/cMisc_TimeSource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_ADUsePolicy/cWDS_ADUsePolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_AddBootimage/cWDS_AddBootimage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_AddImageGroup/cWDS_AddImageGroup.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_AddInstallimage/cWDS_AddInstallimage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_AddUnattendFile/cWDS_AddUnattendFile.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_AnswerPolicy/cWDS_AnswerPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_Authorization/cWDS_Authorization.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_BannedGuidPolicy/cWDS_BannedGuidPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_BcdRefreshPolicy/cWDS_BcdRefreshPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_ClientLogging/cWDS_ClientLogging.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_DefaultBootImage/cWDS_DefaultBootImage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_DefaultBootProgram/cWDS_DefaultBootProgram.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_DefaultN12BootProgram/cWDS_DefaultN12BootProgram.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_DriverGroup/cWDS_DriverGroup.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_DriverPackage/cWDS_DriverPackage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_ImageUnattendFile/cWDS_ImageUnattendFile.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_Initialize/cWDS_Initialize.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_InterfaceBindPolicy/cWDS_InterfaceBindPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_MulticastSessionPolicy/cWDS_MulticastSessionPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_PendingDevicePolicy/cWDS_PendingDevicePolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_PendingDeviceSettings/cWDS_PendingDeviceSettings.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_PrestageDevice/cWDS_PrestageDevice.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_PxeDhcpPolicy/cWDS_PxeDhcpPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_PxePromptPolicy/cWDS_PxePromptPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_RefreshPeriod/cWDS_RefreshPeriod.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_ResetBootProgram/cWDS_ResetBootProgram.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_SetDriverGroupFilter/cWDS_SetDriverGroupFilter.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_TransportNetworkConfig/cWDS_TransportNetworkConfig.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_UnattendFile/cWDS_UnattendFile.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/cWDS/DSCResources/cWDS_UnattendPolicy/cWDS_UnattendPolicy.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xFailOverCluster/DSCResources/MSFT_xCluster/MSFT_xCluster.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xFailOverCluster/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xFailOverCluster/DSCResources/MSFT_xClusterNetwork/MSFT_xClusterNetwork.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xFailOverCluster/DSCResources/MSFT_xClusterPreferredOwner/MSFT_xClusterPreferredOwner.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xFailOverCluster/DSCResources/MSFT_xClusterQuorum/MSFT_xClusterQuorum.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xFailOverCluster/DSCResources/MSFT_xWaitForCluster/MSFT_xWaitForCluster.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xArchive/MSFT_xArchive.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xDSCWebService/MSFT_xDSCWebService.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xEnvironmentResource/MSFT_xEnvironmentResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xGroupResource/MSFT_xGroupResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xMsiPackage/MSFT_xMsiPackage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xPSSessionConfiguration/MSFT_xPSSessionConfiguration.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xPackageResource/MSFT_xPackageResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xRegistryResource/MSFT_xRegistryResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xRemoteFile/MSFT_xRemoteFile.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xScriptResource/MSFT_xScriptResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xServiceResource/MSFT_xServiceResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xUserResource/MSFT_xUserResource.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xWindowsFeature/MSFT_xWindowsFeature.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xWindowsOptionalFeature/MSFT_xWindowsOptionalFeature.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xWindowsPackageCab/MSFT_xWindowsPackageCab.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xPSDesiredStateConfiguration/DSCResources/MSFT_xWindowsProcess/MSFT_xWindowsProcess.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xDisk3/MSFT_xDisk3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xMountImage/MSFT_xMountImage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xWaitForDisk3/MSFT_xWaitForDisk3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/DSCResources/MSFT_xWaitForVolume/MSFT_xWaitForVolume.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xDisk/MSFT_xDisk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xDisk3/MSFT_xDisk3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xDiskAccessPath/MSFT_xDiskAccessPath.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xMountImage/MSFT_xMountImage.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xWaitForDisk/MSFT_xWaitForDisk.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xWaitForDisk3/MSFT_xWaitForDisk3.schema.mof")
#pragma include ("/etc/puppetlabs/code/environments/puppetdev_bob/modules/dsc/import/dsc_resources/xStorage/Modules/xStorage/DSCResources/MSFT_xWaitForVolume/MSFT_xWaitForVolume.schema.mof")
